name: hail
dependencies:
- python=3.6
- nose
- Sphinx=1.7
- sphinxcontrib
- conda-forge::nbsphinx
- conda-forge::sphinx_rtd_theme
- decorator
- numpy
- pandas
- matplotlib
- seaborn
- bokeh
- pip
- pip:
    - parsimonious
    - ipykernel
